/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefLink
 */
export interface RefLink {
    /**
     * 
     * @type {string}
     * @memberof RefLink
     */
    idString?: string;
}

/**
 * Check if a given object implements the RefLink interface.
 */
export function instanceOfRefLink(value: object): value is RefLink {
    return true;
}

export function RefLinkFromJSON(json: any): RefLink {
    return RefLinkFromJSONTyped(json, false);
}

export function RefLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefLink {
    if (json == null) {
        return json;
    }
    return {
        
        'idString': json['id_string'] == null ? undefined : json['id_string'],
    };
}

export function RefLinkToJSON(value?: RefLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id_string': value['idString'],
    };
}

