/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePlayer,
  Player,
} from '../models/index';
import {
    CreatePlayerFromJSON,
    CreatePlayerToJSON,
    PlayerFromJSON,
    PlayerToJSON,
} from '../models/index';

export interface ApiPlayersCreateOnePostRequest {
    body?: CreatePlayer;
}

/**
 * 
 */
export class PlayersApi extends runtime.BaseAPI {

    /**
     */
    async apiPlayersCreateOnePostRaw(requestParameters: ApiPlayersCreateOnePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Player>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/players/create-one`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayerFromJSON(jsonValue));
    }

    /**
     */
    async apiPlayersCreateOnePost(requestParameters: ApiPlayersCreateOnePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Player> {
        const response = await this.apiPlayersCreateOnePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPlayersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Player>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/players`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlayerFromJSON));
    }

    /**
     */
    async apiPlayersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Player>> {
        const response = await this.apiPlayersGetRaw(initOverrides);
        return await response.value();
    }

}
