/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreatePlayerParams
 */
export interface CreatePlayerParams {
    /**
     * 
     * @type {string}
     * @memberof CreatePlayerParams
     */
    'tg_username'?: string;
}
/**
 * 
 * @export
 * @interface CreateTaskParamsSchema
 */
export interface CreateTaskParamsSchema {
    /**
     * 
     * @type {CreateTaskParamsSchemaDescription}
     * @memberof CreateTaskParamsSchema
     */
    'description'?: CreateTaskParamsSchemaDescription;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskParamsSchema
     */
    'link'?: string;
    /**
     * 
     * @type {CreateTaskParamsSchemaDescription}
     * @memberof CreateTaskParamsSchema
     */
    'name'?: CreateTaskParamsSchemaDescription;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskParamsSchema
     */
    'resource'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskParamsSchema
     */
    'resource_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskParamsSchema
     */
    'reward'?: number;
}
/**
 * 
 * @export
 * @interface CreateTaskParamsSchemaDescription
 */
export interface CreateTaskParamsSchemaDescription {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskParamsSchemaDescription
     */
    'en'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskParamsSchemaDescription
     */
    'ru'?: string;
}
/**
 * 
 * @export
 * @interface DeleteTaskParamsSchema
 */
export interface DeleteTaskParamsSchema {
    /**
     * 
     * @type {string}
     * @memberof DeleteTaskParamsSchema
     */
    'id'?: string;
}
/**
 * 
 * @export
 * @interface PlayerSchema
 */
export interface PlayerSchema {
    /**
     * 
     * @type {string}
     * @memberof PlayerSchema
     */
    'birthday'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerSchema
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerSchema
     */
    'id'?: string;
    /**
     * 
     * @type {object}
     * @memberof PlayerSchema
     */
    'physical_characteristics'?: object;
    /**
     * 
     * @type {object}
     * @memberof PlayerSchema
     */
    'psychological_characteristics'?: object;
    /**
     * 
     * @type {string}
     * @memberof PlayerSchema
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerSchema
     */
    'user_id'?: string;
}
/**
 * 
 * @export
 * @interface RegisterUserByTgIdParams
 */
export interface RegisterUserByTgIdParams {
    /**
     * 
     * @type {number}
     * @memberof RegisterUserByTgIdParams
     */
    'parent_tg_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof RegisterUserByTgIdParams
     */
    'tg_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserByTgIdParams
     */
    'tg_username'?: string;
}
/**
 * 
 * @export
 * @interface TaskCompleteParamsSchema
 */
export interface TaskCompleteParamsSchema {
    /**
     * 
     * @type {string}
     * @memberof TaskCompleteParamsSchema
     */
    'task_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskCompleteParamsSchema
     */
    'tg_user_id'?: number;
}
/**
 * 
 * @export
 * @interface TaskCompletedResponseSchema
 */
export interface TaskCompletedResponseSchema {
    /**
     * 
     * @type {boolean}
     * @memberof TaskCompletedResponseSchema
     */
    'is_completed'?: boolean;
}
/**
 * 
 * @export
 * @interface TaskSchema
 */
export interface TaskSchema {
    /**
     * 
     * @type {string}
     * @memberof TaskSchema
     */
    'created_at'?: string;
    /**
     * 
     * @type {CreateTaskParamsSchemaDescription}
     * @memberof TaskSchema
     */
    'description'?: CreateTaskParamsSchemaDescription;
    /**
     * 
     * @type {string}
     * @memberof TaskSchema
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskSchema
     */
    'link'?: string;
    /**
     * 
     * @type {CreateTaskParamsSchemaDescription}
     * @memberof TaskSchema
     */
    'name'?: CreateTaskParamsSchemaDescription;
    /**
     * 
     * @type {string}
     * @memberof TaskSchema
     */
    'resource'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskSchema
     */
    'resource_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskSchema
     */
    'reward'?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskSchema
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface UpdateTaskParamsSchema
 */
export interface UpdateTaskParamsSchema {
    /**
     * 
     * @type {CreateTaskParamsSchemaDescription}
     * @memberof UpdateTaskParamsSchema
     */
    'description'?: CreateTaskParamsSchemaDescription;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskParamsSchema
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskParamsSchema
     */
    'link'?: string;
    /**
     * 
     * @type {CreateTaskParamsSchemaDescription}
     * @memberof UpdateTaskParamsSchema
     */
    'name'?: CreateTaskParamsSchemaDescription;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskParamsSchema
     */
    'resource'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskParamsSchema
     */
    'resource_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTaskParamsSchema
     */
    'reward'?: number;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    'completed_tasks_ids'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'midle_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'parent_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'parent_tg_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'password'?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'sfs_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'tg_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'tg_username'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'ton_wallet_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username'?: string;
}
/**
 * 
 * @export
 * @interface UserGetReferralsQueryParams
 */
export interface UserGetReferralsQueryParams {
    /**
     * 
     * @type {number}
     * @memberof UserGetReferralsQueryParams
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof UserGetReferralsQueryParams
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof UserGetReferralsQueryParams
     */
    'tg_id'?: number;
}

/**
 * PlayersApi - axios parameter creator
 * @export
 */
export const PlayersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreatePlayerParams} [createPlayerParams] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPlayersCreateOnePost: async (createPlayerParams?: CreatePlayerParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/players/create-one`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPlayerParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPlayersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/players`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlayersApi - functional programming interface
 * @export
 */
export const PlayersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlayersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreatePlayerParams} [createPlayerParams] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPlayersCreateOnePost(createPlayerParams?: CreatePlayerParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlayerSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPlayersCreateOnePost(createPlayerParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlayersApi.apiPlayersCreateOnePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPlayersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PlayerSchema>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPlayersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlayersApi.apiPlayersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PlayersApi - factory interface
 * @export
 */
export const PlayersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlayersApiFp(configuration)
    return {
        /**
         * 
         * @param {PlayersApiApiPlayersCreateOnePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPlayersCreateOnePost(requestParameters: PlayersApiApiPlayersCreateOnePostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PlayerSchema> {
            return localVarFp.apiPlayersCreateOnePost(requestParameters.createPlayerParams, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPlayersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<PlayerSchema>> {
            return localVarFp.apiPlayersGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiPlayersCreateOnePost operation in PlayersApi.
 * @export
 * @interface PlayersApiApiPlayersCreateOnePostRequest
 */
export interface PlayersApiApiPlayersCreateOnePostRequest {
    /**
     * 
     * @type {CreatePlayerParams}
     * @memberof PlayersApiApiPlayersCreateOnePost
     */
    readonly createPlayerParams?: CreatePlayerParams
}

/**
 * PlayersApi - object-oriented interface
 * @export
 * @class PlayersApi
 * @extends {BaseAPI}
 */
export class PlayersApi extends BaseAPI {
    /**
     * 
     * @param {PlayersApiApiPlayersCreateOnePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayersApi
     */
    public apiPlayersCreateOnePost(requestParameters: PlayersApiApiPlayersCreateOnePostRequest = {}, options?: RawAxiosRequestConfig) {
        return PlayersApiFp(this.configuration).apiPlayersCreateOnePost(requestParameters.createPlayerParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayersApi
     */
    public apiPlayersGet(options?: RawAxiosRequestConfig) {
        return PlayersApiFp(this.configuration).apiPlayersGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TasksApi - axios parameter creator
 * @export
 */
export const TasksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksAllGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tasks/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {TaskCompleteParamsSchema} [taskCompleteParamsSchema] Task completed params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksCheckCompletePost: async (taskCompleteParamsSchema?: TaskCompleteParamsSchema, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tasks/check-complete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(taskCompleteParamsSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateTaskParamsSchema} [createTaskParamsSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksCreateOnePost: async (createTaskParamsSchema?: CreateTaskParamsSchema, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tasks/create-one`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTaskParamsSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteTaskParamsSchema} [deleteTaskParamsSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksDeleteOneDelete: async (deleteTaskParamsSchema?: DeleteTaskParamsSchema, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tasks/delete-one`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteTaskParamsSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateTaskParamsSchema} [updateTaskParamsSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksUpdateOnePut: async (updateTaskParamsSchema?: UpdateTaskParamsSchema, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tasks/update-one`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTaskParamsSchema, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TasksApi - functional programming interface
 * @export
 */
export const TasksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TasksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTasksAllGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TaskSchema>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTasksAllGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.apiTasksAllGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {TaskCompleteParamsSchema} [taskCompleteParamsSchema] Task completed params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTasksCheckCompletePost(taskCompleteParamsSchema?: TaskCompleteParamsSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskCompletedResponseSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTasksCheckCompletePost(taskCompleteParamsSchema, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.apiTasksCheckCompletePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateTaskParamsSchema} [createTaskParamsSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTasksCreateOnePost(createTaskParamsSchema?: CreateTaskParamsSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTasksCreateOnePost(createTaskParamsSchema, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.apiTasksCreateOnePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteTaskParamsSchema} [deleteTaskParamsSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTasksDeleteOneDelete(deleteTaskParamsSchema?: DeleteTaskParamsSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTasksDeleteOneDelete(deleteTaskParamsSchema, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.apiTasksDeleteOneDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateTaskParamsSchema} [updateTaskParamsSchema] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTasksUpdateOnePut(updateTaskParamsSchema?: UpdateTaskParamsSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTasksUpdateOnePut(updateTaskParamsSchema, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.apiTasksUpdateOnePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TasksApi - factory interface
 * @export
 */
export const TasksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TasksApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksAllGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<TaskSchema>> {
            return localVarFp.apiTasksAllGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TasksApiApiTasksCheckCompletePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksCheckCompletePost(requestParameters: TasksApiApiTasksCheckCompletePostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<TaskCompletedResponseSchema> {
            return localVarFp.apiTasksCheckCompletePost(requestParameters.taskCompleteParamsSchema, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TasksApiApiTasksCreateOnePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksCreateOnePost(requestParameters: TasksApiApiTasksCreateOnePostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<TaskSchema> {
            return localVarFp.apiTasksCreateOnePost(requestParameters.createTaskParamsSchema, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TasksApiApiTasksDeleteOneDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksDeleteOneDelete(requestParameters: TasksApiApiTasksDeleteOneDeleteRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<TaskSchema> {
            return localVarFp.apiTasksDeleteOneDelete(requestParameters.deleteTaskParamsSchema, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TasksApiApiTasksUpdateOnePutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTasksUpdateOnePut(requestParameters: TasksApiApiTasksUpdateOnePutRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<TaskSchema> {
            return localVarFp.apiTasksUpdateOnePut(requestParameters.updateTaskParamsSchema, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiTasksCheckCompletePost operation in TasksApi.
 * @export
 * @interface TasksApiApiTasksCheckCompletePostRequest
 */
export interface TasksApiApiTasksCheckCompletePostRequest {
    /**
     * Task completed params
     * @type {TaskCompleteParamsSchema}
     * @memberof TasksApiApiTasksCheckCompletePost
     */
    readonly taskCompleteParamsSchema?: TaskCompleteParamsSchema
}

/**
 * Request parameters for apiTasksCreateOnePost operation in TasksApi.
 * @export
 * @interface TasksApiApiTasksCreateOnePostRequest
 */
export interface TasksApiApiTasksCreateOnePostRequest {
    /**
     * 
     * @type {CreateTaskParamsSchema}
     * @memberof TasksApiApiTasksCreateOnePost
     */
    readonly createTaskParamsSchema?: CreateTaskParamsSchema
}

/**
 * Request parameters for apiTasksDeleteOneDelete operation in TasksApi.
 * @export
 * @interface TasksApiApiTasksDeleteOneDeleteRequest
 */
export interface TasksApiApiTasksDeleteOneDeleteRequest {
    /**
     * 
     * @type {DeleteTaskParamsSchema}
     * @memberof TasksApiApiTasksDeleteOneDelete
     */
    readonly deleteTaskParamsSchema?: DeleteTaskParamsSchema
}

/**
 * Request parameters for apiTasksUpdateOnePut operation in TasksApi.
 * @export
 * @interface TasksApiApiTasksUpdateOnePutRequest
 */
export interface TasksApiApiTasksUpdateOnePutRequest {
    /**
     * 
     * @type {UpdateTaskParamsSchema}
     * @memberof TasksApiApiTasksUpdateOnePut
     */
    readonly updateTaskParamsSchema?: UpdateTaskParamsSchema
}

/**
 * TasksApi - object-oriented interface
 * @export
 * @class TasksApi
 * @extends {BaseAPI}
 */
export class TasksApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApi
     */
    public apiTasksAllGet(options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).apiTasksAllGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TasksApiApiTasksCheckCompletePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApi
     */
    public apiTasksCheckCompletePost(requestParameters: TasksApiApiTasksCheckCompletePostRequest = {}, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).apiTasksCheckCompletePost(requestParameters.taskCompleteParamsSchema, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TasksApiApiTasksCreateOnePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApi
     */
    public apiTasksCreateOnePost(requestParameters: TasksApiApiTasksCreateOnePostRequest = {}, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).apiTasksCreateOnePost(requestParameters.createTaskParamsSchema, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TasksApiApiTasksDeleteOneDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApi
     */
    public apiTasksDeleteOneDelete(requestParameters: TasksApiApiTasksDeleteOneDeleteRequest = {}, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).apiTasksDeleteOneDelete(requestParameters.deleteTaskParamsSchema, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TasksApiApiTasksUpdateOnePutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TasksApi
     */
    public apiTasksUpdateOnePut(requestParameters: TasksApiApiTasksUpdateOnePutRequest = {}, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).apiTasksUpdateOnePut(requestParameters.updateTaskParamsSchema, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UserGetReferralsQueryParams} [userGetReferralsQueryParams] Telegram id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersReferralsGet: async (userGetReferralsQueryParams?: UserGetReferralsQueryParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users/referrals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userGetReferralsQueryParams !== undefined) {
                for (const [key, value] of Object.entries(userGetReferralsQueryParams)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RegisterUserByTgIdParams} [registerUserByTgIdParams] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersRegisterPost: async (registerUserByTgIdParams?: RegisterUserByTgIdParams, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerUserByTgIdParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUsersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.apiUsersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UserGetReferralsQueryParams} [userGetReferralsQueryParams] Telegram id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersReferralsGet(userGetReferralsQueryParams?: UserGetReferralsQueryParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUsersReferralsGet(userGetReferralsQueryParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.apiUsersReferralsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RegisterUserByTgIdParams} [registerUserByTgIdParams] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUsersRegisterPost(registerUserByTgIdParams?: RegisterUserByTgIdParams, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUsersRegisterPost(registerUserByTgIdParams, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.apiUsersRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<User>> {
            return localVarFp.apiUsersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UsersApiApiUsersReferralsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersReferralsGet(requestParameters: UsersApiApiUsersReferralsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<User>> {
            return localVarFp.apiUsersReferralsGet(requestParameters.userGetReferralsQueryParams, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UsersApiApiUsersRegisterPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUsersRegisterPost(requestParameters: UsersApiApiUsersRegisterPostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.apiUsersRegisterPost(requestParameters.registerUserByTgIdParams, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiUsersReferralsGet operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersReferralsGetRequest
 */
export interface UsersApiApiUsersReferralsGetRequest {
    /**
     * Telegram id
     * @type {UserGetReferralsQueryParams}
     * @memberof UsersApiApiUsersReferralsGet
     */
    readonly userGetReferralsQueryParams?: UserGetReferralsQueryParams
}

/**
 * Request parameters for apiUsersRegisterPost operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersRegisterPostRequest
 */
export interface UsersApiApiUsersRegisterPostRequest {
    /**
     * 
     * @type {RegisterUserByTgIdParams}
     * @memberof UsersApiApiUsersRegisterPost
     */
    readonly registerUserByTgIdParams?: RegisterUserByTgIdParams
}

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public apiUsersGet(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).apiUsersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UsersApiApiUsersReferralsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public apiUsersReferralsGet(requestParameters: UsersApiApiUsersReferralsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).apiUsersReferralsGet(requestParameters.userGetReferralsQueryParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UsersApiApiUsersRegisterPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public apiUsersRegisterPost(requestParameters: UsersApiApiUsersRegisterPostRequest = {}, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).apiUsersRegisterPost(requestParameters.registerUserByTgIdParams, options).then((request) => request(this.axios, this.basePath));
    }
}



