name: Build and Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.0"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract version tag
        id: get_version
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/tags/})"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build and push Docker image for tags
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/sfootball_tgapp:${{ steps.get_version.outputs.version }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Build and push Docker image for main branch
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/sfootball_tgapp:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL_STAGE }}
